site_name: Meowtils Documentation
site_url: https://femboytatp.github.io/meowtils-documentation/

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy

  palette:
    - scheme: slate
      primary: deep_purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Dark mode

    - scheme: default
      primary: deep_purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Light mode

nav:
  - Home: index.md

extra_css:
  - stylesheets/color.css
